"""
Configuration module.
Contains user field indices and game constants.
"""

USER_ID = 0
USERNAME = 1
USER_INFO = 2
USER_AVATAR_ID = 3
TELEGRAM_USERNAME = 4
TELEGRAM_FIRST_NAME = 5
TELEGRAM_LAST_NAME = 6
TELEGRAM_PHONE_NUMBER = 7
COINS = 8
TICKETS = 9
CUPS = 10
VICTORIES = 11
DEFEATS = 12
GAMES_PLAYED = 13
PENALTY_LEFT = 14
PENALTY_SCORED = 15
REFERRALS_COUNT = 16
RECEIVED_COINS = 17
RECEIVED_TICKETS = 18
SMALL_PACKS = 19
MEDIUM_PACKS = 20
BIG_PACKS = 21
GHOST_SMALL_PACKS = 22
GHOST_MEDIUM_PACKS = 23
GHOST_BIG_PACKS = 24
IS_BANNED = 25
BAN_END = 26
WARNS = 27
LEVEL = 28
REGISTER_DATE = 29
LANG = 30
SUCCESS = 31

COINS_START_BALANCE = 10_000
TICKETS_START_BALANCE = 15
PENALTY_RESET_VALUE = 5
MAX_SUCCESS = 1_500_000

VICTORY_COEFFICIENT = 1000
DEFEAT_COEFFICIENT = -1000
SMALL_PACK_COEFFICIENT = 1000
MEDIUM_PACK_COEFFICIENT = 2000
BIG_PACK_COEFFICIENT = 8000
REFERRALS_COEFFICIENT = 3000

GHOST_SMALL_PACKS_COEFFICIENT = SMALL_PACK_COEFFICIENT
GHOST_MEDIUM_PACKS_COEFFICIENT = MEDIUM_PACK_COEFFICIENT
GHOST_BIG_PACKS_COEFFICIENT = BIG_PACK_COEFFICIENT

PENALTY_SUCCESS_REQUIREMENT = 25000
PENALTY_GOAL_REWARD = 3000
PENALTY_WAIT_MIN = 4
PENALTY_WAIT_MAX = 9
PENALTY_MIN_GOALS = 0
PENALTY_MAX_GOALS = 4

MATCH_WIN_COINS_REWARD = 11000
MATCH_WIN_CUPS_REWARD = 10
MATCH_COST_COINS = 5000
MATCH_COST_TICKETS = 1
MATCH_MIN_SCORE = 1
MATCH_MAX_SCORE = 7
MATCH_WAIT_MIN = 5
MATCH_WAIT_MAX = 10

