BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "ClubMembers" (
	"ClubId"	INTEGER NOT NULL,
	"UserId"	INTEGER NOT NULL,
	"CupsForWar"	INTEGER NOT NULL DEFAULT 0,
	"Role"	TEXT NOT NULL DEFAULT 'Member',
	"JoinedAt"	INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "Clubs" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	"Tag"	TEXT NOT NULL UNIQUE,
	"Description"	TEXT,
	"LogoId"	TEXT,
	"Experience"	INTEGER NOT NULL DEFAULT 0,
	"Wins"	INTEGER NOT NULL DEFAULT 0,
	"Defeats"	INTEGER NOT NULL DEFAULT 0,
	"GamesPlayed"	INTEGER NOT NULL DEFAULT 0,
	"LeaderUserId"	INTEGER NOT NULL UNIQUE,
	"MaxMembers"	INTEGER NOT NULL DEFAULT 50,
	"IsPublic"	TEXT NOT NULL DEFAULT 'true',
	"Status"	TEXT NOT NULL DEFAULT 'open',
	"MinimalTrophiesToJoin"	INTEGER NOT NULL DEFAULT 0,
	"CreateDate"	TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"LastWar"	TEXT,
	"ClubWarTrophies"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "LeaderboardUsers" (
	"UserId"	INTEGER NOT NULL,
	"Success"	INTEGER NOT NULL,
	PRIMARY KEY("UserId")
);
CREATE TABLE IF NOT EXISTS "Users" (
	"UserId"	INTEGER NOT NULL UNIQUE,
	"Username"	TEXT NOT NULL,
	"UserInfo"	TEXT,
	"UserAvatarId"	TEXT,
	"TelegramUsername"	TEXT,
	"TelegramFirstName"	TEXT,
	"TelegramLastName"	TEXT,
	"TelegramPhoneNumber"	TEXT,
	"Coins"	INTEGER NOT NULL DEFAULT 10000,
	"Tickets"	INTEGER NOT NULL DEFAULT 5,
	"Cups"	INTEGER NOT NULL DEFAULT 0,
	"Victories"	INTEGER NOT NULL DEFAULT 0,
	"Defeats"	INTEGER NOT NULL DEFAULT 0,
	"GamesPlayed"	INTEGER NOT NULL DEFAULT 0,
	"PenaltyLeft"	INTEGER NOT NULL DEFAULT 5,
	"PenaltyScored"	INTEGER NOT NULL DEFAULT 0,
	"ReferralsCount"	INTEGER NOT NULL DEFAULT 0,
	"ReceivedCoins"	INTEGER NOT NULL DEFAULT 0,
	"ReceivedTickets"	INTEGER NOT NULL DEFAULT 0,
	"GhostSmallPacks"	INTEGER NOT NULL DEFAULT 0,
	"GhostMediumPacks"	INTEGER NOT NULL DEFAULT 0,
	"GhostBigPacks"	INTEGER NOT NULL DEFAULT 0,
	"SmallPacks"	INTEGER NOT NULL DEFAULT 0,
	"MediumPacks"	INTEGER NOT NULL DEFAULT 0,
	"BigPacks"	INTEGER NOT NULL DEFAULT 0,
	"IsBanned"	TEXT NOT NULL DEFAULT 'false',
	"BanEnd"	TEXT,
	"Warns"	INTEGER NOT NULL DEFAULT 0,
	"Level"	INTEGER NOT NULL DEFAULT 4,
	"RegisterDate"	TEXT,
	"Lang"	TEXT DEFAULT 'en_US',
	PRIMARY KEY("UserId")
);
CREATE INDEX IF NOT EXISTS "idx_success" ON "LeaderboardUsers" (
	"Success"	DESC
);
COMMIT;
