"""
User table field indices for easier code maintenance.
Must match the order of columns in the Users table in init.sql.
"""
USER_ID = 0
USERNAME = 1
USER_INFO = 2
USER_AVATAR_ID = 3
TELEGRAM_USERNAME = 4
TELEGRAM_FIRST_NAME = 5
TELEGRAM_LAST_NAME = 6
TELEGRAM_PHONE_NUMBER = 7
COINS = 8
TICKETS = 9
CUPS = 10
VICTORIES = 11
DEFEATS = 12
GAMES_PLAYED = 13
PENALTY_LEFT = 14
PENALTY_SCORED = 15
REFERRALS_COUNT = 16
RECEIVED_COINS = 17
RECEIVED_TICKETS = 18
SMALL_PACKS = 19
MEDIUM_PACKS = 20
BIG_PACKS = 21
GHOST_SMALL_PACKS = 22
GHOST_MEDIUM_PACKS = 23
GHOST_BIG_PACKS = 24
IS_BANNED = 25
BAN_END = 26
WARNS = 27
LEVEL = 28
REGISTER_DATE = 29
LANG = 30
SUCCESS = 31
